"""fase2_preco_do_insumo

Revision ID: 41a3c8772420
Revises: a48e9991d94f
Create Date: 2026-09-09 13:43:19.333767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a3c8772420'
down_revision: Union[str, Sequence[str], None] = 'a48e9991d94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_price_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('preco_pago_centavos', sa.BigInteger(), nullable=False),
    sa.Column('quantidade_comprada', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('custo_por_base_milicentavos', sa.BigInteger(), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('origem', sa.Enum('manual', 'compra', name='origem_preco_enum'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_price_snapshots_business_id'), 'ingredient_price_snapshots', ['business_id'], unique=False)
    op.create_index(op.f('ix_ingredient_price_snapshots_ingredient_id'), 'ingredient_price_snapshots', ['ingredient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_price_snapshots_ingredient_id'), table_name='ingredient_price_snapshots')
    op.drop_index(op.f('ix_ingredient_price_snapshots_business_id'), table_name='ingredient_price_snapshots')
    op.drop_table('ingredient_price_snapshots')
    # ### end Alembic commands ###
