"""fase2_registrar_venda

Revision ID: 54ea71f8f292
Revises: 9aa9e855ce91
Create Date: 2026-09-11 17:42:06.399801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ea71f8f292'
down_revision: Union[str, Sequence[str], None] = '9aa9e855ce91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('financial_period_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('confirmada', 'cancelada', name='status_venda_enum'), nullable=False),
    sa.Column('data_hora_ocorrencia', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_por_user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['channel_id'], ['sales_channels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['criado_por_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_period_id'], ['financial_periods.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_business_id'), 'sales', ['business_id'], unique=False)
    op.create_index(op.f('ix_sales_channel_id'), 'sales', ['channel_id'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('preco_unitario_praticado_centavos', sa.BigInteger(), nullable=False),
    sa.Column('custo_total_do_item_centavos', sa.BigInteger(), nullable=False),
    sa.Column('civ_centavos', sa.BigInteger(), nullable=False),
    sa.Column('embalagem_centavos', sa.BigInteger(), nullable=False),
    sa.Column('mao_de_obra_centavos', sa.BigInteger(), nullable=False),
    sa.Column('taxa_percentual_canal', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('taxa_fixa_canal_centavos', sa.BigInteger(), nullable=False),
    sa.Column('imposto_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('margem_contribuicao_unitaria_centavos', sa.BigInteger(), nullable=False),
    sa.Column('margem_contribuicao_total_centavos', sa.BigInteger(), nullable=False),
    sa.Column('margem_contribuicao_percentual', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('origem_preco_tipo', sa.Enum('recomendado', 'estrategico', name='origem_preco_venda_enum'), nullable=False),
    sa.Column('foi_arredondado', sa.Boolean(), nullable=False),
    sa.Column('preco_antes_do_arredondamento_centavos', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_business_id'), 'sale_items', ['business_id'], unique=False)
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    op.add_column('inventory_movements', sa.Column('origem_sale_item_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'inventory_movements', 'sale_items', ['origem_sale_item_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_column('inventory_movements', 'origem_sale_item_id')
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_business_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_sales_channel_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_business_id'), table_name='sales')
    op.drop_table('sales')
    # ### end Alembic commands ###
