"""fase2_combo

Revision ID: 613c0c3fb508
Revises: dd82c7d4f6f5
Create Date: 2026-09-12 11:11:59.073048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '613c0c3fb508'
down_revision: Union[str, Sequence[str], None] = 'dd82c7d4f6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Alembic não cria o tipo enum automaticamente antes de um ADD COLUMN
    # isolado (só faz isso dentro de CREATE TABLE) — criado manualmente aqui.
    op.execute("CREATE TYPE tipo_produto_enum AS ENUM ('simples', 'combo')")
    op.create_table('combo_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('combo_product_id', sa.UUID(), nullable=False),
    sa.Column('component_product_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['combo_product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['component_product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('combo_product_id', 'component_product_id', name='uq_combo_item_component')
    )
    op.create_index(op.f('ix_combo_items_business_id'), 'combo_items', ['business_id'], unique=False)
    op.create_index(op.f('ix_combo_items_combo_product_id'), 'combo_items', ['combo_product_id'], unique=False)
    op.create_index(op.f('ix_combo_items_component_product_id'), 'combo_items', ['component_product_id'], unique=False)
    op.add_column('products', sa.Column('tipo', sa.Enum('simples', 'combo', name='tipo_produto_enum', create_type=False), nullable=False, server_default='simples'))
    op.alter_column('products', 'recipe_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'recipe_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('products', 'tipo')
    op.drop_index(op.f('ix_combo_items_component_product_id'), table_name='combo_items')
    op.drop_index(op.f('ix_combo_items_combo_product_id'), table_name='combo_items')
    op.drop_index(op.f('ix_combo_items_business_id'), table_name='combo_items')
    op.drop_table('combo_items')
    op.execute("DROP TYPE tipo_produto_enum")
    # ### end Alembic commands ###
