"""fase2_canal_de_venda

Revision ID: 725eea1d5b55
Revises: 61bc34b242c6
Create Date: 2026-09-09 18:33:42.234662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '725eea1d5b55'
down_revision: Union[str, Sequence[str], None] = '61bc34b242c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_channels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('taxa_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('taxa_fixa_centavos', sa.BigInteger(), nullable=False),
    sa.Column('imposto_override_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_channels_business_id'), 'sales_channels', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_channels_business_id'), table_name='sales_channels')
    op.drop_table('sales_channels')
    # ### end Alembic commands ###
