"""fase2_precificacao

Revision ID: 9aa9e855ce91
Revises: 725eea1d5b55
Create Date: 2026-09-11 13:03:44.948865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aa9e855ce91'
down_revision: Union[str, Sequence[str], None] = '725eea1d5b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_channel_pricings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('margem_desejada_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('preco_manual_centavos', sa.BigInteger(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['channel_id'], ['sales_channels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'channel_id', name='uq_pricing_product_channel')
    )
    op.create_index(op.f('ix_product_channel_pricings_business_id'), 'product_channel_pricings', ['business_id'], unique=False)
    op.create_index(op.f('ix_product_channel_pricings_channel_id'), 'product_channel_pricings', ['channel_id'], unique=False)
    op.create_index(op.f('ix_product_channel_pricings_product_id'), 'product_channel_pricings', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_channel_pricings_product_id'), table_name='product_channel_pricings')
    op.drop_index(op.f('ix_product_channel_pricings_channel_id'), table_name='product_channel_pricings')
    op.drop_index(op.f('ix_product_channel_pricings_business_id'), table_name='product_channel_pricings')
    op.drop_table('product_channel_pricings')
    # ### end Alembic commands ###
