"""fase1_base_business_auth_financial_period

Revision ID: 9e18fe9166d9
Revises: 
Create Date: 2026-09-08 16:37:19.986363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e18fe9166d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('segment', sa.Enum('hamburgueria', 'pizzaria', 'lanchonete', 'restaurante', 'delivery', 'dark_kitchen', 'cafeteria', 'acaiteria', 'confeitaria', 'marmitaria', 'food_truck', 'pastelaria', 'sorveteria', 'outro', name='segmento_enum'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='BRL', nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('result_entity_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'idempotency_key', name='uq_idempotency_business_key')
    )
    op.create_table('operation_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('volume_mensal_estimado', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('imposto_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('custo_hora_funcionario_centavos', sa.BigInteger(), nullable=False),
    sa.Column('metodo_rateio', sa.Enum('horas_produtivas', name='metodo_rateio_enum'), nullable=False),
    sa.Column('cmv_alvo_max', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('margem_alvo_alta', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('margem_alvo_baixa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('margem_perigosa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('contrib_alvo_alta', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('contrib_alvo_baixa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('aliquota_imposto_lucro', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('modo_proporcionalizacao_fixo', sa.Enum('mes_cheio', 'proporcional_dias', name='modo_proporcionalizacao_enum'), nullable=False),
    sa.Column('dias_operacao_por_mes', sa.Integer(), nullable=True),
    sa.Column('alertar_taxa_zero', sa.Boolean(), nullable=False),
    sa.Column('base_comissao_padrao', sa.Enum('valor_reconhecido_estabelecimento', 'valor_pago_cliente', name='base_comissao_enum'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', name='uq_operation_config_business')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_business_id'), 'users', ['business_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('financial_periods',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_por_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['criado_por_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_periods_business_id'), 'financial_periods', ['business_id'], unique=False)
    op.create_index('uq_financial_period_one_open_per_business', 'financial_periods', ['business_id'], unique=True, postgresql_where=sa.text('data_hora_fim IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_financial_period_one_open_per_business', table_name='financial_periods', postgresql_where=sa.text('data_hora_fim IS NULL'))
    op.drop_index(op.f('ix_financial_periods_business_id'), table_name='financial_periods')
    op.drop_table('financial_periods')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_business_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('operation_configs')
    op.drop_table('idempotency_records')
    op.drop_table('revoked_tokens')
    op.drop_table('businesses')
    # ### end Alembic commands ###
