"""fase2_ingredient_cadastro_basico

Revision ID: a48e9991d94f
Revises: 9e18fe9166d9
Create Date: 2026-09-09 13:30:58.260938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48e9991d94f'
down_revision: Union[str, Sequence[str], None] = '9e18fe9166d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('unidade_compra', sa.Enum('kg', 'g', 'L', 'ml', 'un', name='unidade_compra_enum'), nullable=False),
    sa.Column('perda_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estoque_minimo', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_business_id'), 'ingredients', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredients_business_id'), table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
