"""fase2_custo_fixo_despesa_fechamento

Revision ID: b1c70059f052
Revises: 2cb618c93706
Create Date: 2026-09-14 12:35:00.982896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c70059f052'
down_revision: Union[str, Sequence[str], None] = '2cb618c93706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_costs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('valor_mensal_centavos', sa.BigInteger(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixed_costs_business_id'), 'fixed_costs', ['business_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('financial_period_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('financeira', 'nao_operacional', name='tipo_despesa_enum'), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('valor_centavos', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_por_user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['criado_por_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_period_id'], ['financial_periods.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_business_id'), 'expenses', ['business_id'], unique=False)
    op.create_index(op.f('ix_expenses_financial_period_id'), 'expenses', ['financial_period_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_financial_period_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_business_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_fixed_costs_business_id'), table_name='fixed_costs')
    op.drop_table('fixed_costs')
    # ### end Alembic commands ###
