"""fase2_pizza_fracionada

Revision ID: c736bfe8661d
Revises: 613c0c3fb508
Create Date: 2026-09-14 11:30:43.354601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c736bfe8661d'
down_revision: Union[str, Sequence[str], None] = '613c0c3fb508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Adiciona 'pizza_fracionada' ao enum de tipo de produto (Alembic não
    # detecta valores novos de enum automaticamente no Postgres).
    op.execute("ALTER TYPE tipo_produto_enum ADD VALUE IF NOT EXISTS 'pizza_fracionada'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza_sabores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('pizza_product_id', sa.UUID(), nullable=False),
    sa.Column('sabor_product_id', sa.UUID(), nullable=False),
    sa.Column('fracao', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pizza_product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sabor_product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pizza_product_id', 'sabor_product_id', name='uq_pizza_sabor')
    )
    op.create_index(op.f('ix_pizza_sabores_business_id'), 'pizza_sabores', ['business_id'], unique=False)
    op.create_index(op.f('ix_pizza_sabores_pizza_product_id'), 'pizza_sabores', ['pizza_product_id'], unique=False)
    op.create_index(op.f('ix_pizza_sabores_sabor_product_id'), 'pizza_sabores', ['sabor_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pizza_sabores_sabor_product_id'), table_name='pizza_sabores')
    op.drop_index(op.f('ix_pizza_sabores_pizza_product_id'), table_name='pizza_sabores')
    op.drop_index(op.f('ix_pizza_sabores_business_id'), table_name='pizza_sabores')
    op.drop_table('pizza_sabores')
    # ### end Alembic commands ###
