"""fase2_devolucao_parcial

Revision ID: dd82c7d4f6f5
Revises: 53ae1bc8a0d0
Create Date: 2026-09-11 20:43:59.653370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd82c7d4f6f5'
down_revision: Union[str, Sequence[str], None] = '53ae1bc8a0d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Adiciona 'devolucao_parcial' ao enum de origem do movimento de estoque
    # (Alembic não detecta valores novos de enum automaticamente no Postgres).
    op.execute("ALTER TYPE origem_movimento_enum ADD VALUE IF NOT EXISTS 'devolucao_parcial'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partial_returns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('sale_item_id', sa.UUID(), nullable=False),
    sa.Column('quantidade_devolvida', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_por_user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['criado_por_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partial_returns_business_id'), 'partial_returns', ['business_id'], unique=False)
    op.create_index(op.f('ix_partial_returns_sale_item_id'), 'partial_returns', ['sale_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partial_returns_sale_item_id'), table_name='partial_returns')
    op.drop_index(op.f('ix_partial_returns_business_id'), table_name='partial_returns')
    op.drop_table('partial_returns')
    # ### end Alembic commands ###
