"""fase2_promocoes

Revision ID: f744f969596d
Revises: c736bfe8661d
Create Date: 2026-09-14 11:46:32.212785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f744f969596d'
down_revision: Union[str, Sequence[str], None] = 'c736bfe8661d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo_desconto', sa.Enum('percentual', 'valor_fixo', name='tipo_desconto_enum'), nullable=False),
    sa.Column('desconto_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('desconto_fixo_centavos', sa.BigInteger(), nullable=True),
    sa.Column('percentual_canal', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subsidio_maximo_centavos', sa.BigInteger(), nullable=True),
    sa.Column('vigente_desde', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vigente_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['channel_id'], ['sales_channels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_business_id'), 'promotions', ['business_id'], unique=False)
    op.create_index(op.f('ix_promotions_channel_id'), 'promotions', ['channel_id'], unique=False)
    op.create_index(op.f('ix_promotions_product_id'), 'promotions', ['product_id'], unique=False)
    op.create_index('uq_promotion_one_active_per_product_channel', 'promotions', ['product_id', 'channel_id'], unique=True, postgresql_where=sa.text('ativo IS true'))
    op.add_column('sale_items', sa.Column('preco_tabela_centavos', sa.BigInteger(), nullable=True))
    op.add_column('sale_items', sa.Column('desconto_bancado_estabelecimento_centavos', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('sale_items', sa.Column('desconto_subsidiado_canal_centavos', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('sale_items', sa.Column('promotion_id', sa.UUID(), nullable=True))
    # Dado histórico: antes de Promoções existir, "preço praticado" JÁ ERA o
    # preço de tabela (desconto sempre zero) — preenche as vendas antigas
    # corretamente antes de tornar a coluna obrigatória, em vez de um valor
    # fixo arbitrário que distorceria o histórico.
    op.execute("UPDATE sale_items SET preco_tabela_centavos = preco_unitario_praticado_centavos WHERE preco_tabela_centavos IS NULL")
    op.alter_column('sale_items', 'preco_tabela_centavos', nullable=False)
    op.create_foreign_key(None, 'sale_items', 'promotions', ['promotion_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.drop_column('sale_items', 'promotion_id')
    op.drop_column('sale_items', 'desconto_subsidiado_canal_centavos')
    op.drop_column('sale_items', 'desconto_bancado_estabelecimento_centavos')
    op.drop_column('sale_items', 'preco_tabela_centavos')
    op.drop_index('uq_promotion_one_active_per_product_channel', table_name='promotions', postgresql_where=sa.text('ativo IS true'))
    op.drop_index(op.f('ix_promotions_product_id'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_channel_id'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_business_id'), table_name='promotions')
    op.drop_table('promotions')
    # ### end Alembic commands ###
